### ISSUE TITLE
Add Dependabot configurations to keep project dependencies updated

### ISSUE THREAD

**Issue by Jarmos-san** [developersIndia/developersIndia.in#25]
As the project grows & more dependencies are added to the project, Dependabot will help in keeping a track of them. This issue will track the progress made on adding and/or updating a minimal Dependabot configuration until the developersIndia website is up & running.

For reference on how to configure Dependabot, check out the official docs at: "[Keeping your dependencies updated automatically](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically)".

**Comment by 1Gokul** [comment]
Hey, can I work on this?

I'll just need a couple more details to add to the `dependabot.yml` file. 

- Is a label required for Dependabot's PRs and if yes, what should it be? _(Something like `type:dependencies` etc.)_?
- Do we have to add assignees and/or reviewers ?

**Comment by Jarmos-san** [comment]
Hey @1Gokul thanks for taking the initiative! I've assigned the issue thread to you, so please feel free to go ahead & reference a PR to this thread.

As for your questions;
1. Yes, the `dependencies` label should be good enough for now. We can review it later on if a need arises.
2. Yes, please add @Jarmos-san @varshney-himanshu @Bhupesh-V as reviewers.

**Comment by 1Gokul** [comment]
Thanks!
Please add the new `dependencies` label for the bot.
