### ISSUE TITLE
Add a basic `tsconfig.json` for full TypeScript support in the project.

### ISSUE THREAD

**Issue by Jarmos-san** [developersIndia/developersIndia.in#26]
TypeScript not only provides "type safety" for JavaScript code but in general helps maintaining standard development practices in a project. As such, right now is the best opportunity to add TypeScript support for the project since it can be quite difficult to get started up again later on when the project is moving ahead already.

For more reference on setting up a proper [`tsconfig.json`](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html) file, refer to it's official documentations: https://www.typescriptlang.org/tsconfig

**Comment by siddhantk232** [comment]
can I work on this?

**Comment by Jarmos-san** [comment]
@siddhantk232 yeahs sure, go ahead & reference a PR to this issue!

**Comment by Bhupesh-V** [comment]
@all-contributors please add @siddhantk232 for code
