### ISSUE TITLE
Add/update a CONTRIBUTING.md for contributing guidelines

### ISSUE THREAD

**Issue by siddhantk232** [developersIndia/developersIndia.in#29]
### Feature details?

A guide on how to contribute to this project would be helpful.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jarmos-san** [comment]
@siddhantk232 thanks for taking the initiative! ❤️ 

For starters, use [this contributing guidelines](https://github.com/developersIndia/.github/blob/main/CONTRIBUTING.md) as a source of inspiration to write one which is specific to this project. Also include steps to setup a local dev environment & other important details any contributor would need to know.
